<?php
declare(strict_types = 1);

namespace app\common\controller;

class ApiBase extends Base {
    protected $model;
    protected $validate;
    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!empty($this->getdata['wrtoken']) && !empty($this->getdata['wruid']) && !empty($this->getdata['wrtimes'])){
            if($this->getdata['wrtoken'] == 'null' || $this->getdata['wruid'] == 'null' || $this->getdata['wrtimes'] == 'null'){
                $this->result('','10000','请登录');
            }
            $D_USER = getUser($this->getdata['wruid'],'uid');
            if(!$D_USER){
                $this->result('','10000','请登录');
            }
            $D_USER['wrtimes'] = $this->getdata['wrtimes'];
            if(!$this->res_returntoken($D_USER,$this->getdata['wrtoken'])){
                $this->result('','10000','请登录');
            }
            $this->wormuser = $D_USER;
        }
    }

}