<?php
declare(strict_types = 1);

namespace app\admin\controller;

use app\common\controller\AdminBase;
use app\common\wormview\AddEditList;

class Navclass extends AdminBase {
    use AddEditList;
    protected function initialize(){
        parent::initialize();
        $models = "app\\common\\model\\NavClass";
        $this->validate = "app\\common\\validate\\NavClass";
        $this->contauth = $this->CheckAuth('create,edit,del');
        $this->model = new $models;
        $this->getConf();
    }
    protected function getConf(){
        $this->list_file = [
            ['file' => 'id','title' => 'ID','type' => 'text','width' => '80','textalign' => 'center','fixed' => 'left'],
            ['file' => 'title','title' => '分类名称','type' => $this->contauth['edit'] ? 'edit' : 'text','width' => '40%'],
            ['file' => 'sort','title' => '排序','type' => $this->contauth['edit'] ? 'edit' : 'text','textalign' => 'center','width' => '80'],
            ['file' => 'level','title' => '二级导航','type' => 'switch','width' => '100','text' => '启用|禁用','textalign' => 'center','default' => '1'],
            ['file' => 'status','title' => '状态','type' => 'switch','text' => '启用|禁用','textalign' => 'center','width' => '100','default' => '1']
        ];
        if($this->request->action() == 'index'){
            $this->list_base['page'] = '2';
            if ($this->contauth['create']) {
                $this->list_base['add'] = ['title' => '添加分类','class' => 'cx-button-s cx-bg-green'];
            }
            if($this->contauth['edit']){
                $this->list_file[] = ['filed' => 'edit','title' => '编辑','type' => 'btn','text' => true,'open' => true,'opentitle' => "编辑导航分类",'uri' => url('edit',['id' => '__id__'])->build(),'icon' => 'cx-iconbianji3 cx-text-f16','class' => 'cx-text-green','textalign' => 'center','width' => '80','fixed' => 'right'];
            }
            if($this->contauth['del']){
                $this->list_file[] = ['filed' => 'del','title' => '删除','type' => 'btn','event' => 'del','text' => true,'icon' => 'cx-iconlajixiang cx-text-f16','class' => 'cx-text-red','textalign' => 'center','width' => '80','fixed' => 'right'];
            }
        }else if(in_array($this->request->action(),['edit','create'])) {
            $this->list_base['uri'] = url('save', $this->request->action() == 'create' ? [] : ['id' => $this->getdata['id']]);
            $this->form_list = [
                ['file' => 'title','title' => '分类名称','type' => 'text','required' => true],
                ['file' => 'level','title' => '二级导航','type' => 'radio','data' =>['list' => ['0' => '禁用','1' => '启用',],'default' => '0']],
                ['file' => 'status','title' => '是否启用','type' => 'radio','data' =>['list' => ['0' => '禁用','1' => '启用',],'default' => '1']],
                ['file' => 'sort','title' => '排序值','type' => 'text','type_edit' => 'number','required' => true,'default' => '0','tip' => '数字越大排序越靠前'],
                ];
            if($this->request->action() == 'edit'){
                $phsh = [
                    ['file' => 'id','title' => 'ID','type' => 'text','type_edit' => 'hidden','required' => true,'required_list' => 'number',],
                    ['file' => '_method','title' => 'ID','type' => 'text','type_edit' => 'hidden','required' => true,'default' => 'PUT',]
                ];
                $this->form_list = array_merge($this->form_list,$phsh);
            }
        }
    }
    protected function getOrder(){
        return "sort desc,id asc";
    }
    protected function getMap(){
        $map = [
            'status' => !isset($this->getdata['status']) ? 'a' : $this->getdata['status'],
            'del_time' => empty($this->getdata['del_time']) ? '0' : $this->getdata['del_time']
        ];
        return array_merge(parent::getMap(),$map); // TODO: Change the autogenerated stub
    }
}