<?php
declare(strict_types = 1);

namespace app\api\controller;

use app\common\controller\ApiBase;
use app\common\wormview\AddEditList;
use app\facade\hook\Common;

class Payche extends ApiBase
{
    use AddEditList;
    protected $payModel;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!$this->isLogin()){
            $this->result('','10000','请登录');
        }
        $model = "app\\common\\model\\PayChe";
        $payModel = "app\\common\\model\\PayBase";
        $this->model = new $model;
        $this->payModel = new $payModel;
    }
    public function save()
    {
        if(!$this->request->isPost()){
            $this->result('','0','非法访问');
        }
        $data = Common::data_trim(input('post.'));
        $data['_del'] = empty($data['_del']) ? '0' : $data['_del'];
        $shoplist = [];
        foreach ($data['shoplist'] as $k => $v){
            $v['chinacode'] = empty($data['chinacode']) ? '' : $data['chinacode'];
            $v = $this->payModel->getArticle($v,$this->wormuser,false);
            $shoplist[] = $v;
        }
        $shoplist = array_column($shoplist,'shoplist');
        $_shoplist = [];
        foreach ($shoplist as $k => $v){
            $_shoplist = array_merge($_shoplist,$v);
        }
        $_shoplist = $this->model->editList($_shoplist,$this->wormuser['uid'],$data['_del'] == '1' ? true : false);
        $_id = empty($_shoplist['id']) ? '' : $_shoplist['id'];
        unset($_shoplist['id']);
        $_data = [
            'id' => $_id,
            'uid' => $this->wormuser['uid'],
            'cont' => json_encode($_shoplist,JSON_UNESCAPED_UNICODE),
            'addtime' => time()
        ];
        if($add = $this->model->setOne($_data)){
            $this->result('','1',$data['_del'] == '1' ? '删除成功' : '加入购物车成功');
        }
        $this->result('','0',$data['_del'] == '1' ? '删除失败' : '加入购物车失败');
    }
    public function read()
    {
        return $this->viewApiRead($this->model->getOne($this->wormuser['uid']));
    }
}